### ISSUE TITLE
Отображается только один кейс в Allure репорте

### ISSUE THREAD

**Issue by StasGrishaevTutu** [robotomize/go-allure#26]
Привет ! Спасибо за утилиту, позволяет почти без вложений получить минимальный Allure репорт !
Заметил странность, возможно бага - по какой то причине в репорте по 5 файлам, в которых суммарно содержится больше 20 тестов отображается только один тест, выглядит это так ( проверил в обычном Allure и Allure Testops ) : 
- ![image](https://github.com/robotomize/go-allure/assets/115224622/a0be9954-9ad4-4b71-a05e-70e01e0ba05b)
- ![image](https://github.com/robotomize/go-allure/assets/115224622/13819b27-6032-43c5-be5f-6c448f7cfcd0)

Вижу что в сгенерённых json файлах у всех идёт одинаковое значение testCaseId, причём всегда, для любого теста/запуска - `"testCaseId":"d41d8cd98f00b204e9800998ecf8427e"` Прогнал тесты в твоей репе в дебаге, вижу что там значение такое же, возможно, какой то косяк в коде. 
На всякий случай приложу json от go test и полученные по нему json для Allure - [jsons.zip](https://github.com/robotomize/go-allure/files/11895256/jsons.zip)

Запускаю так - `go clean -testcache && godotenv -f .env go test -json ./tst/account_tests/password_tests/...|golurectl -l -e -s -v -o ./allure-results`

Будет круто, если получится исправить, хотелось бы воспользоваться утилитой в бою) 
Если нужна какая то помощь в воспроизведении - рад помочь !

**Comment by robotomize** [comment]
Привет! Спасибо за фидбек, сегодня/завтра посмотрю внимательно ишью и постараюсь исправить

**Comment by robotomize** [comment]
@StasGrishaevTutu можешь посмотреть локально testcaseID у тебя в своих тестах одинаковый?

**Comment by robotomize** [comment]
А в allure отправляешь как? Есть ощущение, что может отправляется 1 файл отчета только? 
Примерно в gitlab как-то так

**Comment by robotomize** [comment]
А в allure отправляешь как? Есть ощущение, что может отправляется 1 файл отчета только?
Примерно в gitlab как-то так
`  ALLURE_LAUNCH_NAME: '${CI_PROJECT_NAME} - ${CI_COMMIT_SHORT_SHA}'
  ALLURE_LAUNCH_TAGS: "UNIT,ACCEPTANCE"
  ALLURE_REPORTS_FOLDER: ${CI_PROJECT_DIR}/reports`

`  after_script:
    - |
      export TIMESTAMP=$(date);
      export ALLURE_LAUNCH_NAME=${ALLURE_LAUNCH_NAME}" - "${TIMESTAMP};

      if [ -d "${ALLURE_REPORTS_FOLDER}" ]; then
        if [ -n "$(ls -A ${ALLURE_REPORTS_FOLDER} 2>/dev/null)" ]; then
          allurectl auth login -e "${ALLURE_ENDPOINT}" -t "${ALLURE_TOKEN}";
          allurectl upload --launch-tags "${ALLURE_LAUNCH_TAGS}" "${ALLURE_REPORTS_FOLDER}";
        fi
      fi`

**Comment by robotomize** [comment]
Кажется проблему понял, можешь сказать версию еще golurectl version ?

**Comment by StasGrishaevTutu** [comment]
```
golurectl version
golurectl version 0.13.2 darwin arm64
```

**Comment by robotomize** [comment]
Спасибо за данные, я вчера проанализировал, примерное резюме. 
Причина почему тесты не отображаются в том, что ты и заметил, у них одинаковый testCaseID. Я его считаю как md5 от fullName, он уникален для каждого тест кейса. Но в твоих данных testCaseID == d41d8cd98f00b204e9800998ecf8427e это md5 от пустой строки, хотя fullName явно не пустой. Скорее всего ошибка в последних коммитах. За выходные постараюсь исправить

**Comment by StasGrishaevTutu** [comment]
Супер, спасибо !

**Comment by robotomize** [comment]
Как вариант экспериментов можешь глянуть версию `go install github.com/robotomize/go-allure/cmd/golurectl@v0.12.2` Она работает в тестовом контуре, таких проблем не было

**Comment by StasGrishaevTutu** [comment]
> Как вариант экспериментов можешь глянуть версию `go install github.com/robotomize/go-allure/cmd/golurectl@v0.12.2` Она работает в тестовом контуре, таких проблем не было. К сожалению я не прикручивал теги в docker, поэтому только через go install

подтверждаю, тут работает, буду пока на этой версии)
